Installation fix
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'.

>Preparing metadata (setup.py) ... error
>  error: subprocess-exited-with-error
>
>  × python setup.py egg_info did not run successfully.
>  │ exit code: 1
>  ╰─> [18 lines of output]
>      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
>      rather than 'sklearn' for pip commands.